"""empty message

Revision ID: f22fb784b64b
Revises: 739aa4180dde
Create Date: 2023-12-10 16:52:23.739375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22fb784b64b'
down_revision = '739aa4180dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages', sa.String(length=200), nullable=True))
        batch_op.drop_column('page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('pages')

    # ### end Alembic commands ###
